global_costmap:
   global_frame: /map
   robot_base_frame: /base_footprint
   update_frequency: 1.5
   publish_frequency: 1.0
   static_map: true
   rolling_window: false
   resolution: 0.05
   transform_tolerance: 0.5 #0.5-travis #1.0
   map_type: costmap

# GlobalPlanner:        
#    allow_unknown: true 
