// Generated by gencpp from file obrobot_navigation/PoseManageResponse.msg
// DO NOT EDIT!


#ifndef OBROBOT_NAVIGATION_MESSAGE_POSEMANAGERESPONSE_H
#define OBROBOT_NAVIGATION_MESSAGE_POSEMANAGERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <obrobot_navigation/PoseDefine.h>

namespace obrobot_navigation
{
template <class ContainerAllocator>
struct PoseManageResponse_
{
  typedef PoseManageResponse_<ContainerAllocator> Type;

  PoseManageResponse_()
    : status()
    , posedefine()  {
    }
  PoseManageResponse_(const ContainerAllocator& _alloc)
    : status(_alloc)
    , posedefine(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _status_type;
  _status_type status;

   typedef  ::obrobot_navigation::PoseDefine_<ContainerAllocator>  _posedefine_type;
  _posedefine_type posedefine;





  typedef boost::shared_ptr< ::obrobot_navigation::PoseManageResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::obrobot_navigation::PoseManageResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PoseManageResponse_

typedef ::obrobot_navigation::PoseManageResponse_<std::allocator<void> > PoseManageResponse;

typedef boost::shared_ptr< ::obrobot_navigation::PoseManageResponse > PoseManageResponsePtr;
typedef boost::shared_ptr< ::obrobot_navigation::PoseManageResponse const> PoseManageResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::obrobot_navigation::PoseManageResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::obrobot_navigation::PoseManageResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace obrobot_navigation

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'obrobot_navigation': ['/home/pi/autoslam_gm/src/obrobot_navigation/msg', '/home/pi/autoslam_gm/src/obrobot_navigation/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::obrobot_navigation::PoseManageResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::obrobot_navigation::PoseManageResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::obrobot_navigation::PoseManageResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::obrobot_navigation::PoseManageResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::obrobot_navigation::PoseManageResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::obrobot_navigation::PoseManageResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::obrobot_navigation::PoseManageResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3ee0d3f1402669f95ae05bb612a861fa";
  }

  static const char* value(const ::obrobot_navigation::PoseManageResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3ee0d3f1402669f9ULL;
  static const uint64_t static_value2 = 0x5ae05bb612a861faULL;
};

template<class ContainerAllocator>
struct DataType< ::obrobot_navigation::PoseManageResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "obrobot_navigation/PoseManageResponse";
  }

  static const char* value(const ::obrobot_navigation::PoseManageResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::obrobot_navigation::PoseManageResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string status\n\
obrobot_navigation/PoseDefine posedefine\n\
\n\
\n\
================================================================================\n\
MSG: obrobot_navigation/PoseDefine\n\
uint32 id\n\
string name\n\
string type\n\
uint32 floor\n\
geometry_msgs/Pose pose\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::obrobot_navigation::PoseManageResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::obrobot_navigation::PoseManageResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
      stream.next(m.posedefine);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PoseManageResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::obrobot_navigation::PoseManageResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::obrobot_navigation::PoseManageResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.status);
    s << indent << "posedefine: ";
    s << std::endl;
    Printer< ::obrobot_navigation::PoseDefine_<ContainerAllocator> >::stream(s, indent + "  ", v.posedefine);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OBROBOT_NAVIGATION_MESSAGE_POSEMANAGERESPONSE_H
