// Generated by gencpp from file obrobot_navigation/PoseManage.msg
// DO NOT EDIT!


#ifndef OBROBOT_NAVIGATION_MESSAGE_POSEMANAGE_H
#define OBROBOT_NAVIGATION_MESSAGE_POSEMANAGE_H

#include <ros/service_traits.h>


#include <obrobot_navigation/PoseManageRequest.h>
#include <obrobot_navigation/PoseManageResponse.h>


namespace obrobot_navigation
{

struct PoseManage
{

typedef PoseManageRequest Request;
typedef PoseManageResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PoseManage
} // namespace obrobot_navigation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::obrobot_navigation::PoseManage > {
  static const char* value()
  {
    return "ced5f2372deedb2a41f03ed0ae9a8337";
  }

  static const char* value(const ::obrobot_navigation::PoseManage&) { return value(); }
};

template<>
struct DataType< ::obrobot_navigation::PoseManage > {
  static const char* value()
  {
    return "obrobot_navigation/PoseManage";
  }

  static const char* value(const ::obrobot_navigation::PoseManage&) { return value(); }
};


// service_traits::MD5Sum< ::obrobot_navigation::PoseManageRequest> should match 
// service_traits::MD5Sum< ::obrobot_navigation::PoseManage > 
template<>
struct MD5Sum< ::obrobot_navigation::PoseManageRequest>
{
  static const char* value()
  {
    return MD5Sum< ::obrobot_navigation::PoseManage >::value();
  }
  static const char* value(const ::obrobot_navigation::PoseManageRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::obrobot_navigation::PoseManageRequest> should match 
// service_traits::DataType< ::obrobot_navigation::PoseManage > 
template<>
struct DataType< ::obrobot_navigation::PoseManageRequest>
{
  static const char* value()
  {
    return DataType< ::obrobot_navigation::PoseManage >::value();
  }
  static const char* value(const ::obrobot_navigation::PoseManageRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::obrobot_navigation::PoseManageResponse> should match 
// service_traits::MD5Sum< ::obrobot_navigation::PoseManage > 
template<>
struct MD5Sum< ::obrobot_navigation::PoseManageResponse>
{
  static const char* value()
  {
    return MD5Sum< ::obrobot_navigation::PoseManage >::value();
  }
  static const char* value(const ::obrobot_navigation::PoseManageResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::obrobot_navigation::PoseManageResponse> should match 
// service_traits::DataType< ::obrobot_navigation::PoseManage > 
template<>
struct DataType< ::obrobot_navigation::PoseManageResponse>
{
  static const char* value()
  {
    return DataType< ::obrobot_navigation::PoseManage >::value();
  }
  static const char* value(const ::obrobot_navigation::PoseManageResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OBROBOT_NAVIGATION_MESSAGE_POSEMANAGE_H
