// Generated by gencpp from file obrobot_navigation/PoseDefine.msg
// DO NOT EDIT!


#ifndef OBROBOT_NAVIGATION_MESSAGE_POSEDEFINE_H
#define OBROBOT_NAVIGATION_MESSAGE_POSEDEFINE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace obrobot_navigation
{
template <class ContainerAllocator>
struct PoseDefine_
{
  typedef PoseDefine_<ContainerAllocator> Type;

  PoseDefine_()
    : id(0)
    , name()
    , type()
    , floor(0)
    , pose()  {
    }
  PoseDefine_(const ContainerAllocator& _alloc)
    : id(0)
    , name(_alloc)
    , type(_alloc)
    , floor(0)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef uint32_t _id_type;
  _id_type id;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _type_type;
  _type_type type;

   typedef uint32_t _floor_type;
  _floor_type floor;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::obrobot_navigation::PoseDefine_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::obrobot_navigation::PoseDefine_<ContainerAllocator> const> ConstPtr;

}; // struct PoseDefine_

typedef ::obrobot_navigation::PoseDefine_<std::allocator<void> > PoseDefine;

typedef boost::shared_ptr< ::obrobot_navigation::PoseDefine > PoseDefinePtr;
typedef boost::shared_ptr< ::obrobot_navigation::PoseDefine const> PoseDefineConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::obrobot_navigation::PoseDefine_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::obrobot_navigation::PoseDefine_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace obrobot_navigation

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'obrobot_navigation': ['/home/pi/autoslam_gm/src/obrobot_navigation/msg', '/home/pi/autoslam_gm/src/obrobot_navigation/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::obrobot_navigation::PoseDefine_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::obrobot_navigation::PoseDefine_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::obrobot_navigation::PoseDefine_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::obrobot_navigation::PoseDefine_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::obrobot_navigation::PoseDefine_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::obrobot_navigation::PoseDefine_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::obrobot_navigation::PoseDefine_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4961e9ce48eeb076d10e966f73b4f21b";
  }

  static const char* value(const ::obrobot_navigation::PoseDefine_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4961e9ce48eeb076ULL;
  static const uint64_t static_value2 = 0xd10e966f73b4f21bULL;
};

template<class ContainerAllocator>
struct DataType< ::obrobot_navigation::PoseDefine_<ContainerAllocator> >
{
  static const char* value()
  {
    return "obrobot_navigation/PoseDefine";
  }

  static const char* value(const ::obrobot_navigation::PoseDefine_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::obrobot_navigation::PoseDefine_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 id\n\
string name\n\
string type\n\
uint32 floor\n\
geometry_msgs/Pose pose\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::obrobot_navigation::PoseDefine_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::obrobot_navigation::PoseDefine_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.name);
      stream.next(m.type);
      stream.next(m.floor);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PoseDefine_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::obrobot_navigation::PoseDefine_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::obrobot_navigation::PoseDefine_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.id);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.type);
    s << indent << "floor: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.floor);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OBROBOT_NAVIGATION_MESSAGE_POSEDEFINE_H
