// Generated by gencpp from file obrobot_navigation/PoseOperation.msg
// DO NOT EDIT!


#ifndef OBROBOT_NAVIGATION_MESSAGE_POSEOPERATION_H
#define OBROBOT_NAVIGATION_MESSAGE_POSEOPERATION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace obrobot_navigation
{
template <class ContainerAllocator>
struct PoseOperation_
{
  typedef PoseOperation_<ContainerAllocator> Type;

  PoseOperation_()
    : opt()
    , id(0)
    , name()
    , type()
    , floor(0)  {
    }
  PoseOperation_(const ContainerAllocator& _alloc)
    : opt(_alloc)
    , id(0)
    , name(_alloc)
    , type(_alloc)
    , floor(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _opt_type;
  _opt_type opt;

   typedef uint32_t _id_type;
  _id_type id;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _type_type;
  _type_type type;

   typedef uint32_t _floor_type;
  _floor_type floor;





  typedef boost::shared_ptr< ::obrobot_navigation::PoseOperation_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::obrobot_navigation::PoseOperation_<ContainerAllocator> const> ConstPtr;

}; // struct PoseOperation_

typedef ::obrobot_navigation::PoseOperation_<std::allocator<void> > PoseOperation;

typedef boost::shared_ptr< ::obrobot_navigation::PoseOperation > PoseOperationPtr;
typedef boost::shared_ptr< ::obrobot_navigation::PoseOperation const> PoseOperationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::obrobot_navigation::PoseOperation_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::obrobot_navigation::PoseOperation_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace obrobot_navigation

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'obrobot_navigation': ['/home/pi/autoslam_gm/src/obrobot_navigation/msg', '/home/pi/autoslam_gm/src/obrobot_navigation/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::obrobot_navigation::PoseOperation_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::obrobot_navigation::PoseOperation_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::obrobot_navigation::PoseOperation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::obrobot_navigation::PoseOperation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::obrobot_navigation::PoseOperation_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::obrobot_navigation::PoseOperation_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::obrobot_navigation::PoseOperation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a3c8f0bce74dfc0445629cc8fb5aa8a9";
  }

  static const char* value(const ::obrobot_navigation::PoseOperation_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa3c8f0bce74dfc04ULL;
  static const uint64_t static_value2 = 0x45629cc8fb5aa8a9ULL;
};

template<class ContainerAllocator>
struct DataType< ::obrobot_navigation::PoseOperation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "obrobot_navigation/PoseOperation";
  }

  static const char* value(const ::obrobot_navigation::PoseOperation_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::obrobot_navigation::PoseOperation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string opt\n\
uint32 id\n\
string name\n\
string type\n\
uint32 floor\n\
";
  }

  static const char* value(const ::obrobot_navigation::PoseOperation_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::obrobot_navigation::PoseOperation_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.opt);
      stream.next(m.id);
      stream.next(m.name);
      stream.next(m.type);
      stream.next(m.floor);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PoseOperation_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::obrobot_navigation::PoseOperation_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::obrobot_navigation::PoseOperation_<ContainerAllocator>& v)
  {
    s << indent << "opt: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.opt);
    s << indent << "id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.id);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.type);
    s << indent << "floor: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.floor);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OBROBOT_NAVIGATION_MESSAGE_POSEOPERATION_H
