// Generated by gencpp from file obrobot_tools/check_msgActionGoal.msg
// DO NOT EDIT!


#ifndef OBROBOT_TOOLS_MESSAGE_CHECK_MSGACTIONGOAL_H
#define OBROBOT_TOOLS_MESSAGE_CHECK_MSGACTIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <obrobot_tools/check_msgGoal.h>

namespace obrobot_tools
{
template <class ContainerAllocator>
struct check_msgActionGoal_
{
  typedef check_msgActionGoal_<ContainerAllocator> Type;

  check_msgActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  check_msgActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::obrobot_tools::check_msgGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::obrobot_tools::check_msgActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::obrobot_tools::check_msgActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct check_msgActionGoal_

typedef ::obrobot_tools::check_msgActionGoal_<std::allocator<void> > check_msgActionGoal;

typedef boost::shared_ptr< ::obrobot_tools::check_msgActionGoal > check_msgActionGoalPtr;
typedef boost::shared_ptr< ::obrobot_tools::check_msgActionGoal const> check_msgActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::obrobot_tools::check_msgActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::obrobot_tools::check_msgActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace obrobot_tools

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'obrobot_tools': ['/home/pi/autoslam_gm/devel/share/obrobot_tools/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::obrobot_tools::check_msgActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::obrobot_tools::check_msgActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::obrobot_tools::check_msgActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::obrobot_tools::check_msgActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::obrobot_tools::check_msgActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::obrobot_tools::check_msgActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::obrobot_tools::check_msgActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "af0d74cabd74ebfcc5fc9f4d06e38e9e";
  }

  static const char* value(const ::obrobot_tools::check_msgActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaf0d74cabd74ebfcULL;
  static const uint64_t static_value2 = 0xc5fc9f4d06e38e9eULL;
};

template<class ContainerAllocator>
struct DataType< ::obrobot_tools::check_msgActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "obrobot_tools/check_msgActionGoal";
  }

  static const char* value(const ::obrobot_tools::check_msgActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::obrobot_tools::check_msgActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalID goal_id\n\
check_msgGoal goal\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalID\n\
# The stamp should store the time at which this goal was requested.\n\
# It is used by an action server when it tries to preempt all\n\
# goals that were requested before a certain time\n\
time stamp\n\
\n\
# The id provides a way to associate feedback and\n\
# result message with specific goal requests. The id\n\
# specified must be unique.\n\
string id\n\
\n\
\n\
================================================================================\n\
MSG: obrobot_tools/check_msgGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal definition\n\
string imu\n\
string method\n\
float32 distance\n\
float32 angule\n\
float32 vel\n\
float32 error\n\
";
  }

  static const char* value(const ::obrobot_tools::check_msgActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::obrobot_tools::check_msgActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct check_msgActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::obrobot_tools::check_msgActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::obrobot_tools::check_msgActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::obrobot_tools::check_msgGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OBROBOT_TOOLS_MESSAGE_CHECK_MSGACTIONGOAL_H
