local_costmap:

   global_frame: /odom
   #global_frame: /odom_combined
   robot_base_frame: /base_footprint
   update_frequency: 5.0 #5.0-travis #3.0
   publish_frequency: 2.0 #2.0-travis #1.0
   static_map: false
   rolling_window: true
   width: 4.0 #8.0-travis #3.0 # 4 zark
   height: 4.0 #8.0-travis #3.0 #4 zark
   resolution: 0.05
   transform_tolerance: 0.5 #0.5-travis #1.0
   map_type: costmap

   plugins:
  #  - {name: static_layer,        type: "costmap_2d::StaticLayer"}
   - {name: obstacle_layer,      type: "costmap_2d::VoxelLayer"}
   - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}
